# Docs : https://circleci.com/docs/2.0/configuration-reference
# Orb: https://circleci.com/developer/orbs/orb/circleci/node
# Docker executor: https://circleci.com/docs/2.0/executor-types/
# Convenience Images: https://circleci.com/developer/images/image/cimg/node

version: 2.1

orbs:
  node: circleci/node@5.0.0
  codecov: codecov/codecov@3.2.2

jobs:
  api-unit-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests with JUnit as reporter
          command: npx jest --ci --runInBand --reporters=default --reporters=jest-junit
          no_output_timeout: 1m
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

  api-coverage:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run coverage tests
          command: npx jest --runInBand --coverage
          no_output_timeout: 1m
      - codecov/upload

  api-build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: docker build . -t tuk-api
      - run:
          name: Push to Google Artifact Registry
          command: |
            echo -n $GCLOUD_SERVICE_KEY | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project trigpointinguk
            gcloud auth configure-docker $GCR
            docker tag tuk-api $TAG:latest
            docker tag tuk-api $TAG:$CIRCLE_SHA1
            docker tag tuk-api $TAG:$CIRCLE_BUILD_NUM
            docker tag tuk-api $TAG:$(echo -n $CIRCLE_BRANCH | sed 's%/%_%g')
            docker push        $TAG

  api-deploy-tme:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to GCP
          command: |
            echo -n $GCLOUD_SERVICE_KEY | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project trigpointinguk
      - run:
          name: Deploy to Cloud Run - api-tme
          command: |
            gcloud run deploy api-tme \
              --image=$TAG:$CIRCLE_SHA1 \
              --region=$REGION \
              --service-account=api-tme@trigpointinguk.iam.gserviceaccount.com \
              --allow-unauthenticated \
              --port=3000 \
              --memory=4Gi \
              --max-instances=2 \
              --min-instances=0 \
              --update-env-vars \
            MODE=DEV,\
            RUN_MIGRATIONS=true,\
            NEST_DEBUG=true,\
            AUTH0_ISSUER_URL=https://teasel.eu.auth0.com/,\
            AUTH0_AUDIENCE=https://api.trigpointing.me,\
            AUTH0_REDIRECT_URL=https://api.trigpointing.me/docs/oauth2-redirect.html,\
            NODE_TLS_REJECT_UNAUTHORIZED=0, \
              --update-secrets \
            POSTGRES_HOST=TME_POSTGRES_HOST:latest,\
            POSTGRES_PORT=TME_POSTGRES_PORT:latest,\
            POSTGRES_USER=TME_POSTGRES_USER:latest,\
            POSTGRES_PASSWORD=TME_POSTGRES_PASSWORD:latest,\
            POSTGRES_DATABASE=TME_POSTGRES_DATABASE:latest,\
            AUTH0_CLIENT_ID=TME_SWAGGER_AUTH0_CLIENT_ID:latest,\
      - run:
          name: Retag image
          command: gcloud artifacts docker tags add $TAG:$CIRCLE_SHA1 $TAG:tme

  api-deploy-tuk:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to GCP
          command: |
            echo -n $GCLOUD_SERVICE_KEY | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project trigpointinguk
      - run:
          name: Deploy to Cloud Run - api-tuk
          command: |
            gcloud run deploy api-tuk \
              --image=$TAG:$CIRCLE_SHA1 \
              --region=$REGION \
              --service-account=api-tuk@trigpointinguk.iam.gserviceaccount.com \
              --allow-unauthenticated \
              --port=3000 \
              --memory=4Gi \
              --max-instances=4 \
              --min-instances=0 \
              --update-env-vars \
            MODE=DEV,\
            RUN_MIGRATIONS=true,\
            NEST_DEBUG=true,\
            AUTH0_ISSUER_URL=https://teasel.eu.auth0.com/,\
            AUTH0_AUDIENCE=https://api.trigpointing.me,\
            AUTH0_REDIRECT_URL=https://api.trigpointing.me/docs/oauth2-redirect.html,\
            NODE_TLS_REJECT_UNAUTHORIZED=0, \
              --update-secrets \
            POSTGRES_HOST=TME_POSTGRES_HOST:latest,\
            POSTGRES_PORT=TME_POSTGRES_PORT:latest,\
            POSTGRES_USER=TME_POSTGRES_USER:latest,\
            POSTGRES_PASSWORD=TME_POSTGRES_PASSWORD:latest,\
            POSTGRES_DATABASE=TME_POSTGRES_DATABASE:latest,\
            AUTH0_CLIENT_ID=TME_SWAGGER_AUTH0_CLIENT_ID:latest,\
      - run:
          name: Retag image
          command: gcloud artifacts docker tags add $TAG:$CIRCLE_SHA1 $TAG:tuk

workflows:
  oncommit:
    jobs:
      - api-unit-test
      - api-coverage
      - api-build
      - api-deploy-tme:
          requires:
            - api-unit-test
            - api-build
          filters:
            branches:
              ignore:
                - main
      - api-deploy-tuk:
          requires:
            - api-unit-test
            - api-build
          filters:
            branches:
              only:
                - main
